
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { DarkModeProvider } from '../contexts/DarkModeContext';

const nunito = Nunito_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Rest countries",
  description: "Generated by create next app the contries in the world",
};

export default function RootLayout({ children }) {
  return (
    <DarkModeProvider>
      <html lang="en">
        <body className={`${nunito.className} text-base bg-veryLight`}>
      
        <Header />
        <section className="">
          {children}

        </section>
        
      </body>
      </html>
  </DarkModeProvider>
  );
}
